FROM python:3.9-slim-buster AS base

RUN apt-get update \
&& apt-get install gcc libffi-dev libssl-dev -y \
&& apt-get clean

COPY back/requirements.txt requirements.txt

RUN pip install --user -r requirements.txt

FROM python:3.9-slim-buster

COPY --from=base /root/.local /root/.local

RUN mkdir -p /usr/share/Homeware-LAN/back

WORKDIR /usr/share/Homeware-LAN/back

COPY back/requirements.txt requirements.txt

RUN pip install -r requirements.txt \
&& rm -rf /root/.cache

COPY back/* ./

COPY configuration_templates/ /usr/share/Homeware-LAN/configuration_templates/

RUN chmod +x homeware.sh

ENV PATH="~/.local/bin:${PATH}"

CMD ["./homeware.sh"]
