FROM node:lts-alpine AS base
RUN mkdir /app
WORKDIR /app
COPY front ./
RUN npm install
RUN npm run build

FROM nginx
RUN mkdir /html
COPY --from=base /app /html
COPY configuration_templates/nginx_docker /etc/nginx/conf.d/default.conf