name: Build on release
on:
  release:
    types:
      - released

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-push-be-docker-image:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Set release version env var
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push BE
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile-back
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/homewarelan-back:latest
            ghcr.io/${{ github.repository_owner }}/homewarelan-back:${{ env.RELEASE_VERSION }}
  build-push-fe-docker-image:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Set release version env var
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push FE
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile-nginx
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/homewarelan-nginx:latest
            ghcr.io/${{ github.repository_owner }}/homewarelan-nginx:${{ env.RELEASE_VERSION }}